### ISSUE TITLE
this work with go pro 5??

### ISSUE THREAD

**Issue by isdito** [DenisCarriere/gopro#12]
Hello,

Thank you for your help. This libraries work with go pro 5.

Thank you

**Comment by KonradIT** [comment]
yes it does

**Comment by isdito** [comment]
Hello, 

Thank you I install and it is working:
I could save imagen in the computer, the last image?

poweron()  --> give me a error line 260

![captura](https://cloud.githubusercontent.com/assets/602151/24396465/974c60c6-13a3-11e7-860b-f489310f002b.JPG)

**Comment by KonradIT** [comment]
I see, I'll fix it. you can also use my API http://github.com/konradit/gopro-py-api

**Comment by KonradIT** [comment]
Fixed in 9c73bd2
